#!/usr/bin/env bash
if [ $# -ne 5 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	home_dir="~/"
	full_arg="scp -Ti $1 $3@$2:$home_dir"
	echo "$full_arg"
	# scp -Ti $1 $3@$2:$home_dir
fi
