#!/usr/bin/env bash
# Bash script which installs and confiugres nginx on remote server
apt-get update;
apt-get -y install nginx;
html_content="Hello World!"
echo "$html_content" > /var/www/html/hello.html;
service nginx start
