#!/usr/bin/env bash
# installs nginx and configures it on a remote server
apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
mkdir -p /var/www/redirect_me/
redir_conf="location /redirect_me {
	root /var/www/redirect_me;
	return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}"
sed -i "/s/listen 80/listen 80\n\t$redir_conf/g" /etc/nginx/nginx.conf
service nginx start
