#!/usr/bin/env bash
# Script that configures a new Ubuntu machine to respect above requirements
sudo apt-get update
sudo apt-get install -y nginx

echo "Ceci n'est pas une page" > /var/www/html/404.html
string_for_replacement="\terror_page 404 \/404.html;"
sudo sed -i "/location \//a $string_for_replacement" /etc/nginx/sites-enabled/default

sudo service nginx restart
