#!/usr/bin/env bash
# Bash script which installs and configures HAProxy to set up load balancer
# add-apt-repository ppa:vbernat/haproxy-2.0
# apt-get -y update
# apt-get install -y haproxy=2.0.\*
# haproxy_config=\
# "
# frontend request_80
# 	bind *:80
# 	mode http
# 	default backend two_server
#
# backend two_server
# 	balance roundrobin
# 	server 531140-web-01 54.82.134.192:80 check
# 	server 531140-web-02 54.146.93.43:80 check
# "
# init_config="ENABLED=1"
# echo "$haproxy_config" > /etc/haproxy/haproxy.cfg
# echo "$init_config" > /etc/default/haproxy
# sudo service haproxy restart

sudo apt-get -y update
apt-get -y install haproxy

# edit config file
server_config=\
"
frontend  server_frontend
        bind *:80
        mode http
        default_backend two_server

backend two_server
        balance roundrobin
        server 531140-web-01 54.82.134.192:80 check
        server 531140-web-02 54.146.93.43:80 check
"
echo "$server_config" | sudo tee -a /etc/haproxy/haproxy.cfg

# enable haproxy to be started by init script

echo "ENABLED=1" | sudo tee -a /etc/default/haproxy

haproxy -f /etc/haproxy/haproxy.cfg
sudo service haproxy restart
