#!/usr/bin/env bash
# Bash script which installs and configures HAProxy to set up load balancer
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.0
apt-get install -y haproxy=2.0.\*
mkdir -p /etc/haproxy/
haproxy_config="
frontend request_80
	bind *:80
	mode http

backend two_server
	balance roundrobin
	server 531140-web-01:80
	server 531140-web-02:80
"
echo "$haproxy_config" > /etc/haproxy/haproxy.cfg
