#!/usr/bin/env bash
# Bash script which debugs a remote server to get nginx to listen on port 80
sed -E -i "s/^\s*listen [0-9]{1,5}/\tlisten 80" /etc/nginx/sites-enabled/default
sudo service nginx restart
