#!/usr/bin/env bash
# Bash script which debugs a remote server to get nginx to listen on port 80
sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo rm -rf /var/run/nginx.pid
pkill $( pgrep nginx | head -1 )
