#!/usr/bin/env bash
#Bash script that prints the sentence "Best School" 10 times
#On iteration 9, prints "HI"

i="1"
while [ $i -lt 11 ]; do
if [[ $i -eq 9 ]]; then
		echo "Hi"
else
		echo "Best School"
fi
(( i++ ))
done
