#!/usr/bin/env bash
#Bash script that prints the sentence "Best School" 10 times
#On iteration 9, prints "HI"

i="1"
while [ $i -le 10 ]; do
if [[ $i -eq 4 ]]; then
	echo "bad luck"
elif [[ $i -eq 8 ]]; then
	echo "good luck"
else
	echo "Best School"
fi
(( i++ ))
done
