#!/usr/bin/env bash
#Displays numbers from 1 to 20, prints:
#4, then newline, then bad luck from China
#9, then newline, then bad luck from Japan
#17, then newline, then bad luck from Italy

i="1"
while [ $i -le 20 ]; do
if [[ $i -eq 4 ]]; then
	echo "$i"
	echo "bad luck from China"
elif [[ $i -eq 9 ]]; then
	echo "$i"
	echo "bad luck from Japan"
elif [[ $i -eq 17 ]]; then
	echo "$i"
	echo "bad luck from Italy"
else
	echo "$i"
fi
(( i++ ))
done
