#!/usr/bin/env bash
#Bash script that checks the information of a file
file="./school"

if [ -e $file ]; then
		echo "school file exists"
		#check if file is empty or not
		if [ -s $file ]; then
				echo "school file is not empty"
		else
				echo "school file is empty"
		fi
		#check if file is regular file
		if [ -f $file ]; then
				echo "school is a regular file"
		fi
else
		echo "school file does not exist"
fi
